// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Migrate/introspect need a direct (non-pooled) connection -- Supabase's
// pgbouncer transaction-mode pooler doesn't support the advisory locks and
// prepared statements the schema engine relies on. The app itself connects
// via the pooled DATABASE_URL at runtime (see lib/prisma.ts).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
